package com.qdu.entity;
// Generated 2019-12-1 16:55:01 by Hibernate Tools 4.3.1



import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Buy generated by hbm2java
 */
@Entity
@Table(name="Buy"
    ,schema="dbo"
    ,catalog="C2C"
)
public class Buy  implements java.io.Serializable {


     private String buyId;
     private String uid;
     private String pname;
     private String pbrand;
     private Integer blower;
     private Integer bhigher;
     private String pdesc;
     private Date btime;

    public Buy() {
    }

	
    public Buy(String buyId, String uid) {
        this.buyId = buyId;
        this.uid = uid;
    }
    public Buy(String buyId, String uid, String pname, String pbrand, Integer blower, Integer bhigher, String pdesc, Date btime) {
       this.buyId = buyId;
       this.uid = uid;
       this.pname = pname;
       this.pbrand = pbrand;
       this.blower = blower;
       this.bhigher = bhigher;
       this.pdesc = pdesc;
       this.btime = btime;
    }
   
     @Id 

    
    @Column(name="BuyId", unique=true, nullable=false, length=15)
    public String getBuyId() {
        return this.buyId;
    }
    
    public void setBuyId(String buyId) {
        this.buyId = buyId;
    }

    
    @Column(name="UID", nullable=false, length=15)
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }

    
    @Column(name="PName")
    public String getPname() {
        return this.pname;
    }
    
    public void setPname(String pname) {
        this.pname = pname;
    }

    
    @Column(name="Pbrand")
    public String getPbrand() {
        return this.pbrand;
    }
    
    public void setPbrand(String pbrand) {
        this.pbrand = pbrand;
    }

    
    @Column(name="BLower")
    public Integer getBlower() {
        return this.blower;
    }
    
    public void setBlower(Integer blower) {
        this.blower = blower;
    }

    
    @Column(name="BHigher")
    public Integer getBhigher() {
        return this.bhigher;
    }
    
    public void setBhigher(Integer bhigher) {
        this.bhigher = bhigher;
    }

    
    @Column(name="PDesc")
    public String getPdesc() {
        return this.pdesc;
    }
    
    public void setPdesc(String pdesc) {
        this.pdesc = pdesc;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BTime", length=23)
    public Date getBtime() {
        return this.btime;
    }
    
    public void setBtime(Date btime) {
        this.btime = btime;
    }




}


