package com.qdu.entity;
// Generated 2019-12-1 16:55:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name="Cart"
    ,schema="dbo"
    ,catalog="C2C"
)
public class Cart  implements java.io.Serializable {


     private String cartId;
     private Integer cquantity;
     private String pid; 
     private String pname;
     private String uid;
     private BigDecimal cprice;
     private Date ctime;

    public Cart(String cartId, Integer cquantity, String pid, String pname, String uid, BigDecimal cprice, Date ctime) {
        this.cartId = cartId;
        this.cquantity = cquantity;
        this.pid = pid;
        this.pname = pname;
        this.uid = uid;
        this.cprice = cprice;
        this.ctime = ctime;
    }

    public String getPid() {
        return pid;
    }

    public void setPid(String pid) {
        this.pid = pid;
    }
    

    public Cart() {
    }

	
    public Cart(String cartId) {
        this.cartId = cartId;
    }
  
   
     @Id 

    
    @Column(name="CartId", unique=true, nullable=false, length=15)
    public String getCartId() {
        return this.cartId;
    }
    
    public void setCartId(String cartId) {
        this.cartId = cartId;
    }

    
    @Column(name="Cquantity")
    public Integer getCquantity() {
        return this.cquantity;
    }
    
    public void setCquantity(Integer cquantity) {
        this.cquantity = cquantity;
    }

    
    @Column(name="Pname")
    public String getPname() {
        return this.pname;
    }
    
    public void setPname(String pname) {
        this.pname = pname;
    }

    
    @Column(name="UID", length=15)
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }

    
    @Column(name="CPrice", precision=18)
    public BigDecimal getCprice() {
        return this.cprice;
    }
    
    public void setCprice(BigDecimal cprice) {
        this.cprice = cprice;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CTime", length=23)
    public Date getCtime() {
        return this.ctime;
    }
    
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }




}


