package com.qdu.entity;
// Generated 2019-12-1 16:55:01 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Manager generated by hbm2java
 */
@Entity
@Table(name="Manager"
    ,schema="dbo"
    ,catalog="C2C"
)
public class Manager  implements java.io.Serializable{


     private String aid;
     private String aname;
     private String apwd;

    public Manager() {
    }

    public Manager(String aid, String aname, String apwd) {
       this.aid = aid;
       this.aname = aname;
       this.apwd = apwd;
    }
   
     @Id 

    
    @Column(name="AID", unique=true, nullable=false, length=15)
    public String getAid() {
        return this.aid;
    }
    
    public void setAid(String aid) {
        this.aid = aid;
    }

    
    @Column(name="AName", nullable=false)
    public String getAname() {
        return this.aname;
    }
    
    public void setAname(String aname) {
        this.aname = aname;
    }

    
    @Column(name="APwd", nullable=false)
    public String getApwd() {
        return this.apwd;
    }
    
    public void setApwd(String apwd) {
        this.apwd = apwd;
    }




}


