package com.qdu.entity;
// Generated 2019-12-1 16:55:01 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notice generated by hbm2java
 */
@Entity
@Table(name="Notice"
    ,schema="dbo"
    ,catalog="C2C"
)
public class Notice  implements java.io.Serializable {


     private String ntcId;
     private String content;
     private Date ntime;
     private String ntitle;

    public Notice() {
    }

	
    public Notice(String ntcId, String content) {
        this.ntcId = ntcId;
        this.content = content;
    }
    public Notice(String ntcId, String content, Date ntime, String ntitle) {
       this.ntcId = ntcId;
       this.content = content;
       this.ntime = ntime;
       this.ntitle = ntitle;
    }
   
     @Id 

    
    @Column(name="NtcID", unique=true, nullable=false, length=15)
    public String getNtcId() {
        return this.ntcId;
    }
    
    public void setNtcId(String ntcId) {
        this.ntcId = ntcId;
    }

    
    @Column(name="Content", nullable=false)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="NTime", length=23)
    public Date getNtime() {
        return this.ntime;
    }
    
    public void setNtime(Date ntime) {
        this.ntime = ntime;
    }

    
    @Column(name="NTitle")
    public String getNtitle() {
        return this.ntitle;
    }
    
    public void setNtitle(String ntitle) {
        this.ntitle = ntitle;
    }




}


