package com.qdu.entity;
// Generated 2019-12-1 16:55:01 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProductCategory generated by hbm2java
 */
@Entity
@Table(name="ProductCategory"
    ,schema="dbo"
    ,catalog="C2C"
)
public class ProductCategory  implements java.io.Serializable {


     private String categoryId;
     private String categoryName;
     private String categoryDesc;

    public ProductCategory() {
    }

	
    public ProductCategory(String categoryId, String categoryName) {
        this.categoryId = categoryId;
        this.categoryName = categoryName;
    }
    public ProductCategory(String categoryId, String categoryName, String categoryDesc) {
       this.categoryId = categoryId;
       this.categoryName = categoryName;
       this.categoryDesc = categoryDesc;
    }
   
     @Id 

    
    @Column(name="CategoryID", unique=true, nullable=false, length=15)
    public String getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    
    @Column(name="CategoryName", nullable=false)
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    
    @Column(name="CategoryDesc")
    public String getCategoryDesc() {
        return this.categoryDesc;
    }
    
    public void setCategoryDesc(String categoryDesc) {
        this.categoryDesc = categoryDesc;
    }




}


